# -*- coding: utf-8 -*-
"""Crypto Profit Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18I2O0sA9cq3P2cuSYhJhZk3oFpRnIZG-

Crypto Profit Calculator
"""

def calculate_crypto_profit(entry_price, exit_price, quantity, transaction_fees):
    profit = (exit_price - entry_price) * quantity - transaction_fees
    return profit

# Example usage:
entry_price = 10000  # Replace with your entry price
exit_price = 12000  # Replace with your exit price
quantity = 1        # Replace with the quantity of cryptocurrency
transaction_fees = 10  # Replace with any transaction fees

profit = calculate_crypto_profit(entry_price, exit_price, quantity, transaction_fees)

print(f"Profit: ${profit}")