# -*- coding: utf-8 -*-
"""MatplotLib_graph_hydrogen_bond.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJGjNPV4MbFsl4BMq2r5nKLJPi1s3WrY
"""

import matplotlib.pyplot as plt
import numpy
t,hbond,pairs = numpy.loadtxt("hbnum.xvg", comments=["@", "#"], unpack=True)

fig = plt.figure(figsize=(10,5))
ax = fig.add_subplot(111)


ax.plot(t,hbond, color="black", linestyle="-")
ax.set_xlabel("time $t$ (ps)",fontsize=20, fontweight='bold')
ax.set_ylabel("number of H bonds", fontsize=20, fontweight='bold')

#We change the fontsize of minor ticks label 
ax.tick_params(axis='both', which='major', labelsize=15)
ax.tick_params(axis='both', which='minor', labelsize=8)

plt.savefig("hbnum.png", format="png", dpi=1200)
plt.show()