# -*- coding: utf-8 -*-
"""RDkit_for_compare_physicochemical_pharmacikinetics_properties.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GJerwrz5N84sfKKIgH2wbOyTGk2o82QP
"""

pip install rdkit

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
from rdkit.Chem import MACCSkeys
from rdkit.Chem import DataStructs  # Import DataStructs for TanimotoSimilarity

# Define two molecules as SMILES strings
molecule1_smiles = "CC1=NN=C2C=CC(=NN12)N1N=C(C)C(CCC(=O)N2CCC(CC3=CC=CC=C3)CC2)=C1C"  # Replace with your first molecule's SMILES string
molecule2_smiles = "CC(C)CCN(C)C(=O)C1CCN(CC1)C1=Nn2nnnc2C=C1"  # Replace with your second molecule's SMILES string

# Convert SMILES strings to RDKit molecules
molecule1 = Chem.MolFromSmiles(molecule1_smiles)
molecule2 = Chem.MolFromSmiles(molecule2_smiles)

# Check if molecules are valid
if molecule1 is None or molecule2 is None:
    raise ValueError("One or both of the input molecules are invalid.")

# Calculate molecular fingerprints
fp1 = MACCSkeys.GenMACCSKeys(molecule1)
fp2 = MACCSkeys.GenMACCSKeys(molecule2)

# Calculate Tanimoto similarity
similarity = DataStructs.TanimotoSimilarity(fp1, fp2) * 100

# Calculate molecular descriptors (optional)
logP1 = Descriptors.MolLogP(molecule1)
logP2 = Descriptors.MolLogP(molecule2)
mw1 = Descriptors.MolWt(molecule1)
mw2 = Descriptors.MolWt(molecule2)

# Calculate Lipinski's Rule of Five properties
hbd1 = Descriptors.NumHDonors(molecule1)
hbd2 = Descriptors.NumHDonors(molecule2)
hba1 = Descriptors.NumHAcceptors(molecule1)
hba2 = Descriptors.NumHAcceptors(molecule2)

# Print the results
print(f"Similarity between the two molecules: {similarity:.2f}%")
print(f"Molecular properties for molecule 1 - LogP: {logP1}, Molecular Weight: {mw1}")
print(f"Molecular properties for molecule 2 - LogP: {logP2}, Molecular Weight: {mw2}")
print(f"Lipinski's Rule of Five properties for molecule 1 - HBD: {hbd1}, HBA: {hba1}")
print(f"Lipinski's Rule of Five properties for molecule 2 - HBD: {hbd2}, HBA: {hba2}")