# -*- coding: utf-8 -*-
"""RMSD_XVG_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19RvfigRGi3LEP_l0gYqkdgAI23ynFCg6
"""

# Plot RMSD (for 2 XVG files)
import numpy as np
import matplotlib.pyplot as plt

# Load RMSD data from the first XVG file
data1 = np.loadtxt('rmsd_complex_B7_IL1.xvg', comments=['@', '#'])

# Load RMSD data from the second XVG file
data2 = np.loadtxt('rmsd_complex_positive_IL1.xvg', comments=['@', '#'])

# Convert time from ps to ns (assuming time is in the first column)
time_ns = data1[:, 0] / 1000  # Convert ps to ns

# Extract RMSD values (assuming RMSD is in the second column)
rmsd1 = data1[:, 1]
rmsd2 = data2[:, 1]

# Plot RMSD data
plt.figure(figsize=(10, 6))
plt.plot(time_ns, rmsd1, label='B7-IL1R1 Complex', color='blue')
plt.plot(time_ns, rmsd2, label='Positive Control Complex', color='red')
plt.xlabel('Time (ns)')
plt.ylabel('RMSD (Å)')
plt.title('Root Mean Square Deviation (RMSD) vs. Time')
plt.legend()
plt.grid(True)

# Annotate each file outside the plot box
#plt.text(time_ns[-1] + 1, rmsd1[-1], 'B7-IL1R1 Complex', fontsize=12, color='blue', ha='left', va='center')
#plt.text(time_ns[-1] + 1, rmsd2[-1], 'Positive Control Complex', fontsize=12, color='red', ha='left', va='center')

# Calculate average difference between the two datasets
average_difference = np.mean(np.abs(rmsd1 - rmsd2))
print("Average Difference:", average_difference, "Å")

# Save the plot as JPEG and PDF
plt.savefig('rmsd_plot.jpg', bbox_inches='tight')  # JPEG format
plt.savefig('rmsd_plot.pdf', bbox_inches='tight')  # PDF format

plt.show()

# Plot RMSD (for 3 XVG files)
import numpy as np
import matplotlib.pyplot as plt

# Load RMSD data from the XVG files
data1 = np.loadtxt('rmsd_complex_B7_IL1.xvg', comments=['@', '#'])
data2 = np.loadtxt('rmsd_complex_positive_IL1.xvg', comments=['@', '#'])
data3 = np.loadtxt('rmsd_complex_other.xvg', comments=['@', '#'])

# Convert time from ps to ns (assuming time is in the first column)
time_ns = data1[:, 0] / 1000  # Convert ps to ns

# Extract RMSD values (assuming RMSD is in the second column)
rmsd1 = data1[:, 1]
rmsd2 = data2[:, 1]
rmsd3 = data3[:, 1]

# Plot RMSD data
plt.figure(figsize=(10, 6))
plt.plot(time_ns, rmsd1, label='RMSD File 1', color='blue')
plt.plot(time_ns, rmsd2, label='RMSD File 2', color='red')
plt.plot(time_ns, rmsd3, label='RMSD File 3', color='green')
plt.xlabel('Time (ns)')
plt.ylabel('RMSD (Å)')
plt.title('Root Mean Square Deviation (RMSD) vs. Time')
plt.legend()
plt.grid(True)

# Annotate each file outside the plot box with smaller font size
plt.text(time_ns[-1], rmsd1[-1], 'B7-IL1R1 Complex', fontsize=8, color='blue', ha='right', va='bottom')
plt.text(time_ns[-1], rmsd2[-1], 'Positive Control Complex', fontsize=8, color='red', ha='right', va='bottom')
plt.text(time_ns[-1], rmsd3[-1], 'Other Complex', fontsize=8, color='green', ha='right', va='bottom')

# Calculate average difference between the datasets
average_difference_1_2 = np.mean(np.abs(rmsd1 - rmsd2))
average_difference_1_3 = np.mean(np.abs(rmsd1 - rmsd3))
average_difference_2_3 = np.mean(np.abs(rmsd2 - rmsd3))

print("Average Difference 1-2:", average_difference_1_2, "Å")
print("Average Difference 1-3:", average_difference_1_3, "Å")
print("Average Difference 2-3:", average_difference_2_3, "Å")

# Save the plot as JPEG and PDF
plt.savefig('rmsd_plot.jpg', bbox_inches='tight')  # JPEG format
plt.savefig('rmsd_plot.pdf', bbox_inches='tight')  # PDF format

plt.show()